---
- include: dependencies.yml

- name: checkout SoftEther VPN from source
  git: 
    repo: 'https://github.com/SoftEtherVPN/SoftEtherVPN.git'
    dest: /tmp/softethervpn
    version: v4.22-9634-beta
  register: source

- name: build SoftEther VPN
  command: "{{ item }}"
  args: 
    chdir: /tmp/softethervpn    
    creates: /usr/bin/vpnserver 
  with_items:
    - ./configure
    - make
    - make install
  when: source.changed  

- name: creates lock directory
  file: path=/var/lock/subsys state=directory

- name: install vpnserver init script
  template: >
    src=vpnserver.j2
    dest=/etc/init.d/vpnserver
    mode=0755
  when: se_use_vpnserver

- name: service vpnserver on
  service: >
    name=vpnserver
    enabled=yes
    state=started
  when: se_use_vpnserver

- name: install vpnbridge init script
  template: >
    src=vpnbridge.j2
    dest=/etc/init.d/vpnbridge
    mode=0755
  when: se_use_vpnbridge

- name: service vpnbridge on
  service: >
    name=vpnbridge
    enabled=yes
    state=started
  when: se_use_vpnbridge

- name: install vpnclient init script
  template: >
    src=vpnclient.j2
    dest=/etc/init.d/vpnclient
    mode=0755
  when: se_use_vpnclient

- name: service vpnclient on
  service: >
    name=vpnclient
    enabled=yes
    state=started
  when: se_use_vpnclient
